#!/bin/bash

set -e

SERVER="";
RUSER="";
LDIR=$1;
RDIR=$2;
SSH_OPT="";

export RSYNC_RSH="ssh ${SSH_OPT}";

rsync -avu --progress ${LDIR} ${RUSER}@${SERVER}:${RDIR};

if echo $RDIR | grep -q 'upgrades'; then
  VERSION=$(basename ${LDIR});
  ssh ${SSH_OPT} ${RUSER}@${SERVER} "if [ -a ${RDIR}/latest ]; then rm ${RDIR}/latest; fi";
  ssh ${SSH_OPT} ${RUSER}@${SERVER} "ln -s ${RDIR}/${VERSION} ${RDIR}/latest";
fi
