#!/bin/bash

if [ -d morketsmerke.github.io ]; then rm -rf morketsmerke.github.io; fi
if [ ! -d morketsmerke.github.io ]; then
  git clone https://github.com/morketsmerke/morketsmerke.github.io;
else
  exit 1;
fi

function R() {
  
  if [ "$path" ]; then path=${path}/${1};
  else path=$1;
  fi
  
  fileList=$(ls $path);
  for file in $fileList; do
    if [ -d ${path}/${file} ]; then R ${file};
    else
      sed -i 's@https://morketsmerke.github.io/@/usr/share/doc/morketsmerke/index.html@' ${path}/${file};
      sed -i 's@https://morketsmerke.github.io@/usr/share/doc/morketsmerke/index.html@'  ${path}/${file};
      sed -i 's@/style.css@/usr/share/doc/morketsmerke/style.css@' ${path}/${file};
    fi
  done
  path=$(echo $path | sed "s@/$1@@")

}

R morketsmerke.github.io

sudo mv morketsmerke.github.io /usr/share/doc/morketsmerke
