#!/bin/bash

idx_upgrade_complete() {
 local cur;

  COMPREPLY=();
  cur=${COMP_WORDS[COMP_CWORD]};

  if [ $COMP_CWORD  -eq 1 ]; then
    COMPREPLY=( $(compgen -W '-c -d -h -m -p -s -u -v' -- $cur) );
  elif [ $COMP_CWORD -eq 2 ]; then
    return 0;
  fi
  return 0;
 
}

complete -F idx_upgrade_complete immudex-upgrade

