#!/bin/bash

idx_shoutcasts_complete() {
 local cur prev

  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]};
  prev=${COMP_WORDS[COMP_CWORD-1]}

  if [ $COMP_CWORD -eq 1 ]; then
    COMPREPLY=( $(compgen -W '-s -k -h -v' -- $cur) );
  elif [ $COMP_CWORD -eq 2 ]; then
    case "$prev" in
      '-s') 
          COMPREPLY=( $(compgen -W "icecast radio" -- $cur) )
      ;;
      *) return 0;;
    esac
  fi
  return 0;
}

complete -F idx_shoutcasts_complete immudex-shoutcasts
