#!/bin/bash

cd /tmp
mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old
#wget https://archive.chirpmyradio.com/chirp_next/next-20240319/chirp-20240319-py3-none-any.whl
chirpRepoURL=$(wget -v "https://archive.chirpmyradio.com/download?stream=next" 2>&1 | grep 'Lokaliza
cja:' | head -1 | awk '{printf $2}');
chirpVer=$(basename $chirpRepoURL | cut -d "-" -f 2);
chirpFilename="chirp-${chirpVer}-py3-none-any.whl";
wget ${chirpRepoURL}/${chirpFilename};
pip3 install $chirpFilename;
apt install -y python-wxtools

wget https://ftp.morketsmerke.org/chirp/chirp.desktop -O /usr/share/applications/chirp.desktop;
wget https://ftp.morketsmerke.org/chirp/chirp.png -O /usr/share/pixmaps/chirp.png;
