#!/bin/bash

cd /tmp
mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old
#wget https://archive.chirpmyradio.com/chirp_next/next-20240319/chirp-20240319-py3-none-any.whl
chirpURL="https://ftp.morketsmerke.org/chirp/chirp-20240419-py3-none-any.whl"
wget ${chirpURL};
pip3 install $(basename $chirpURL);
apt install -y python-wxtools

wget https://ftp.morketsmerke.org/chirp/chirp.desktop -O /usr/share/applications/chirp.desktop;
wget https://ftp.morketsmerke.org/chirp/chirp.png -O /usr/share/pixmaps/chirp.png;
