#!/bin/bash

apt install -y qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virtinst libvirt-daemon virt-manager libosinfo-bin;

cp -vv ~/immudex/tools/bin/immudex-kvm /usr/local/bin;

u=$(grep '1000' /etc/passwd | cut -d ":" -f 1)
usermod -aG libvirt,libvirt-qemu $u;

if [ "$DEBVER" = "stable" ]; then
  sed -i '554i dynamic_ownership = 0' /etc/libvirt/qemu.conf;
fi
