#!/bin/bash

set -e 
#Polityka antyfrankenstainowa - 13.05.2024
if [ "$DEBVER" != "testing" ]; then

  if [ "$(uname -m)" != "x86_64" ]; then
    echo "Other architectures than x86_64 (amd64) is not supported by this script";
  fi

  if [ "$DEBVER" = "stable" ]; then
    LibreWolfRepo="https://deb.librewolf.net/pool/bookworm/";
  else
    LibreWolfRepo="https://deb.librewolf.net/pool/bullseye/";
  fi

  wget $LibreWolfRepo -O /tmp/index.html;
  latestLink=$(grep -o '<a href=".*">' /tmp/index.html | sed 's/>/ /g' | cut -d " " -f 2 | sed -n '2,$p' | sed 's/"/ /g' | cut -d " " -f 2 | tail -1);
  filename=$(basename $latestLink);

  wget https://deb.librewolf.net${latestLink} -O /tmp/${filename};
  apt install -y lsb-release libgdk-pixbuf2.0-0;
  dpkg -i /tmp/${filename};
else
  echo "LibreWolf installation is not supported for Debian testing.";
fi
