#!/bin/bash

set -e
if [ ! -f /proc/cpuinfo ]; then
  echo "There is no system interfaces! Nothing to do. Exiting...";
  exit 1;
else
  if [ ! -d /boot ]; then
	    mkdir /boot;
	    apt purge linux-image* --purge -y;
	    apt install linux-image-amd64 -y;
  fi

  cp -vv /etc/apt/sources.list /etc/apt/sources.list.d/nvidia.list;
  sed -e 's/main/contrib non-free non-free-firmware/g' -i /etc/apt/sources.list.d/nvidia.list;
  apt update;
  apt install -y build-essential dkms linux-headers-$(uname -r);
  apt install -y nvidia-detect;
  apt install -y nvidia-driver;
fi
