#!/bin/bash

RED="\e[31m";
GREEN="\e[32m";
ENDCOLOR="\e[0m";

function help() {
  echo "it's a script for installation immudex LiveCD images on computer hard";
  echo "disk. This program runs interactivly and the one thing you need to do";
  echo "is choose a right disk for installation. That's all, but if you using";
  echo "custom images, you may need change partition size for immudex image."
  echo "It's hard to imagine, how it's possible to create images bigger than 3";
  echo "GB. It would happens. More space in this partition is also needed for";
  echo "upgrades tasks. So if your image is bigger than 2 GiB, you need to ";
  echo "change size of this partition before you start instalation.";
  echo "Recomended size is 3 times the image size. The partition size can be";
  echo "changed via below described option.";
  echo "This script requires superuser (root) privileges.";
  echo;
  echo "Usage: immudex-install [--partition-size=3G] [--help] [--version]";
  echo;
  echo "Options:";
  echo "  --partition-size=3G   This option change a partition size with immudex image. Usefull for custom builds. By default it's 3GB.";
  echo "  --help                Print this message.";
  echo "  --version             Print information about version, author and copyrights.";
  echo;
  echo "Examples:";
  echo "  immudex-install                       Standard execution, instalation immudex LiveCD on computer hard disk.";
  echo "  immudex-install --partition-size=6G   Run install script for custom immudex image build.";
  echo "  immudex-install --help                Print this message.";
  echo "  immudex-install --version             Print information about version, author and copyrights.";
  echo;
  echo "Report bugs to <xf0r3m@gmail.com>"; 
}

function version() {
  echo "immudex-install 1.1";
  echo;
  echo "Copyright (C) 2026 morketsmerke.org";
  echo "This is free software; see the source for copying conditions.  There is NO";
  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.";
  echo;
  echo "Written by xf0r3m.";

}

if [ "$1" ]; then
  if [ "$1" = "--help" ]; then
    help;
  elif [ "$1" = "--version" ]; then
    version;
  fi
fi
if [ "$1" ]; then
  if $(echo $1 | grep -q 'partition-size'); then
    idxPartSize=$(echo $1 | cut -d "=" -f2);
  else
    idxPartSize="3G"; 
  fi
else
  idxPartSize="3G"; 
fi

if [ $UID -ne 0 ]; then
  echo "Permission denied!";
  exit 1;
fi

while [ true ]; do
  echo -e "${RED}This script will install immudex on first disk on your machine.${ENDCOLOR}";
  echo -e "${RED}It could be destructive for data placed on this disk${ENDCOLR}";
  echo -en "${RED}Are you sure that you want contiune? (y/n): ${ENDCOLOR}";
  read ans;
  if [ "$ans" = "y" ]; then break;
  elif [ "$ans" = "n" ]; then exit 1;
  fi
done

set -e

function selectDisk() {
  disks=$(lsblk | grep 'disk' | awk '{printf $1" "}');
  if [ $(echo $disks | wc -w) -gt 1 ]; then
    select drive in $disks; do
      echo $drive;
      break;
    done 
  else
	  echo $disks | awk '{printf $1}';
  fi
}

if $(sudo efibootmgr > /dev/null 2>&1); then
#uefi installation
	#partitioning
  echo -n "Installation immudex in EFI mode ... ";
  disk=$(selectDisk);
  originDisk=$disk;   
  if [ ! "$disk" ]; then exit 1; fi

  dd if=/dev/zero bs=1M of=/dev/$disk count=1 2> /dev/null

	parted /dev/$disk mklabel msdos > /dev/null 2>&1;
	parted /dev/$disk mkpart primary 1 101M > /dev/null 2>&1;
	parted /dev/$disk set 1 boot on > /dev/null 2>&1;
	parted /dev/$disk mkpart primary 101M $idxPartSize > /dev/null 2>&1;

  if $(echo $disk | egrep -qo "mmc|nvme"); then disk="${disk}p"; fi
	
	#formatting
	mkfs.vfat -F32 /dev/${disk}1 > /dev/null 2>&1;
	mkfs.ext4 /dev/${disk}2 > /dev/null 2>&1;

  #Setting label for partition
	e2label /dev/${disk}2 "immudex" > /dev/null 2>&1;

	#mount root partition
	mount /dev/${disk}2 /media > /dev/null 2>&1;
	
	#creating directories for efi partition
	mkdir -p /media/boot/efi > /dev/null 2>&1;

	#mount efi partition
	mount /dev/${disk}1 /media/boot/efi > /dev/null 2>&1;

	#mount iso image in /mnt directory
	#sudo mount /dev/sr0 /mnt > /dev/null 2>&1;

	#copying whole iso image to the second partition
	cp -rvv /run/live/medium/* /media > /dev/null 2>&1;
  
  sed -i '/set\ timeout=/ s/30/5/' /media/boot/grub/grub.cfg;  
  sed -i 's/bootfrom=removable //g' /media/boot/grub/grub.cfg; 

	#removing unnecessary directories from second partition
	rm -rf /media/isolinux > /dev/null 2>&1;
	rm -rf /media/EFI > /dev/null 2>&1;

	#GRUB Installation
  if [ -f /usr/lib/live/mount/medium/EFI/BOOT/BOOTIA32.EFI ]; then
    target="i386-efi";
  else
    target="x86_64-efi";
  fi
	grub-install --target=${target} --root-directory=/media --boot-directory=/media/boot --efi-directory=/media/boot/efi --bootloader-id=debian --removable > /dev/null 2>&1;

	#Adding entry to EFI Firmware
	efibootmgr -c -d /dev/${originDisk} -p 1 -L "Debian" -l '\EFI\BOOT\grubx64.efi' > /dev/null 2>&1;

  #Umount all mounted filesystems
  umount -R /media > /dev/null 2>&1;

  if [ $? -eq 0 ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]"; fi

else
#mbr installation
  echo -n "Installation immudex in BIOS mode ... ";

	#partitioning
	disk=$(selectDisk);
  if [ ! "$disk" ]; then exit 1; fi

  dd if=/dev/zero bs=1M of=/dev/$disk count=1 2> /dev/null

  parted /dev/$disk mklabel msdos > /dev/null 2>&1;
	parted /dev/$disk mkpart primary 1 $idxPartSize > /dev/null 2>&1;
	parted /dev/$disk set 1 boot on > /dev/null 2>&1;
	
  if $(echo $disk | egrep -qo "mmc|nvme"); then disk="${disk}p"; fi

	#formatting
	mkfs.ext4 /dev/${disk}1 > /dev/null 2>&1;

	#Setting label for partition is necessary for extlinux bootloader
	e2label /dev/${disk}1 "immudex" > /dev/null 2>&1;

	#mount partition in /media directory
	mount /dev/${disk}1 /media > /dev/null 2>&1;

	#Creating directory for extlinux
	mkdir /media/extlinux > /dev/null 2>&1;
	
	#Instalation extlinux files in abovementioned directory
	extlinux --install /media/extlinux > /dev/null 2>&1;

	#mount iso image in /mnt directory
	#sudo mount /dev/sr0 /mnt > /dev/null 2>&1;

	#copying live directory from iso image to partition
	cp -rvv /run/live/medium/live /media > /dev/null; 2>&1;

	#installation extlinux MBR on first sector of hard drive (whole device)
	dd if=/usr/lib/EXTLINUX/mbr.bin of=/dev/${disk} > /dev/null 2>&1;

	#creating extlinux configuration file
	cat > extlinux.conf <<EOF
default immudex
label immudex
kernel /live/vmlinuz
append quiet initrd=/live/initrd boot=live overlay-size=25% apparmor=1 security=apparmor
EOF
	cp extlinux.conf /media/extlinux > /dev/null 2>&1;
  rm extlinux.conf;

  #Unmounting filesystems
  umount /media > /dev/null 2>&1;
  if [ $? -eq 0 ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]"; fi
fi
