#!/bin/bash

set -e

source library.sh

RED="\e[31m";
GREEN="\e[32m";
YELLOW="\e[33m";
ENDCOLOR="\e[0m";
root="/run/live/medium";

function help() {
  echo "Script for searching upgrades and upgrade immudex.";
  echo "Superuser (root) privileges are required.";
  echo;
  echo "Usage: immudex-upgrade [-c] [-d] [-h] [-m] [-p] [-s] [-u] [-v]";
  echo;
  echo "Options:";
  echo "  -c        Check there are upgrades for immudex";
  echo "  -d        Prints date of image creation";
  echo "  -h        Prints this message.";
  echo "  -m        Prints image details";
  echo "  -p        Updates apt (packages) list and prints available to upgrade packages.";
  echo "  -s        Updates apt (packages) list and prints only packages upgrades from security repository branch";
  echo "  -u        Upgrade immudex from given source";
  echo "  -v        Prints information about version, author and copyrights."; 
  echo;
  echo "Report bugs to <xf0r3m@gmail.com>";
}

function version(){
  echo "immudex-upgrade 1.1";
  echo;
  echo "Copyright (C) 2026 morketsmerke.org";
  echo "This is free software; see the source for copying conditions.  There is NO";
  echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.";
  echo;
  echo "Written by xf0r3m.";
}

if [ $UID -ne 0 ]; then
  echo "Permission denied!";
  help;
  exit 1;
fi

if [ "$1" ]; then
  if [ "$1" = "-h" ]; then
    help;
    exit 0;
  elif [ "$1" = "-v" ]; then
    version;
    exit 0;
  fi
  if [ "$1" ] && [ "$1" = "-c" ]; then
    if check_distro_commit; then 
      echo -e "${GREEN}This${ENDCOLOR} is the latest version of immudex";
    else
      echo -e "There is a ${RED}new${ENDCOLOR} version of immudex:";
      echo "===================================================";
      check_distro_commit --print;
    fi
  elif [ "$1" ] && [ "$1" = "-u" ]; then
    part=$(blkid | grep 'LABEL="immudex"' | awk '{printf $1}' | cut -d ":" -f 1);
    if mount | grep -q "$part"; then
      echo -n "Mounting iso image...";
      mount $2 /mnt > /dev/null 2>&1;
      if [ $? -eq 0 ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]"; fi
      mountPointList=$(mount | grep "$part" | awk '{printf $3" "}');
      for mountPoint in $mountPointList; do
        echo -n "Unlocking $mountPoint ..."; 
        mount $part $mountPoint -o remount,rw > /dev/null 2>&1;
        if [ $? -eq 0 ]; then
          echo -e "[ ${GREEN}OK${ENDCOLOR} ]";
        else
          echo -e "[ ${RED}FAIL${ENDCOLOR} ]";
        fi
      done
      echo "Copying immudex files to the disk...";
      cp -vv /mnt/live/* ${mountPoint}/live;
      if [ $? -eq 0 ]; then
        echo -e "Copying immudex files to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
      else
        echo -e "Copying immudex files to the disk...[ ${RED}FAIL${ENDCOLOR} ]";
      fi
    else
      echo -n "Mounting immudex partition...";
      mount $part /mnt >> /dev/null 2>&1;
      if [ $? -eq 0 ]; then echo -e "[ ${GREEN}OK${ENDCOLOR} ]"; fi
      echo "Copying immudex files to the disk...";
      cp -vv /run/live/medium/live/* /mnt/live;
      if [ $? -eq 0 ]; then
        echo -e "Copying immudex files to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
      else
        echo -e "Copying immudex files to the disk...[ ${RED}FAIL${ENDCOLOR} ]";
      fi
    fi
    if $(sudo efibootmgr > /dev/null 2>&1); then
	    echo "Copying grub config to the disk...";
      if [ "$mountPoint" ]; then
        cp -vv /mnt/boot/grub/grub.cfg ${mountPoint}/boot/grub/grub.cfg;
        if [ $? -eq 0 ]; then 
          echo -e "Copying grub config to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
          sed -i '/set\ timeout=/ s/30/5/' ${mountPoint}/boot/grub/grub.cfg;
	        sed -i 's/bootfrom=removable //g' ${mountPoint}/boot/grub/grub.cfg;
        else
          echo -e "Copying grub config to the disk...[ ${RED}FAIL${ENDCOLOR} ]";
        fi
      else
	      cp -vv /run/live/medium/boot/grub/grub.cfg /mnt/boot/grub/grub.cfg;
	      if [ $? -eq 0 ]; then 
          echo -e "Copying grub config to the disk...[ ${GREEN}OK${ENDCOLOR} ]";
	        sed -i '/set\ timeout=/ s/30/5/' /mnt/boot/grub/grub.cfg;
	        sed -i 's/bootfrom=removable //g' /mnt/boot/grub/grub.cfg;
        else
          echo -e "Copying grub config to the disk...[ ${RED}FAIL${ENDCOLOR} ]";
        fi
      fi
    fi
  elif [ "$1" ] && [ "$1" = "-m" ]; then
    #if [ -d /tmp/immudex ]; then 
    #  (cd /tmp/immudex && git pull > /dev/null 2>&1)
    #else
    #  git clone https://github.com/xf0r3m/immudex /tmp/immudex;
    #fi
    #(cd /tmp/immudex && git show $(cat /run/live/medium/live/version))
    cat /run/live/medium/live/changelog;
  elif [ "$1" ] && [ "$1" = "-p" ]; then
    apt update;
    apt list --upgradable;
  elif [ "$1" ] && [ "$1" = "-s" ]; then
    apt update;
    apt list --upgradable | grep 'security';
  elif [ "$1" ] && [ "$1" = "-d" ]; then
    eval $(grep '^COMPILATION_DATE' /run/live/medium/live/changelog);    
    echo "Image was created: $COMPILATION_DATE";
  else
    help;
    exit 1;
  fi
else
  help;
  exit 1;
fi

