#!/bin/bash

if [ $UID -ne 0 ]; then
  echo "Permission denied!";
  exit 1;
fi

bootID=$(sed 's/-//g' /proc/sys/kernel/random/boot_id | cut -c 26-33);
if hostnamectl > /dev/null 2>&1; then
	hName="$(hostnamectl | grep 'Chassis' | cut -d ":" -f 2 | awk '{printf $1}')-${bootID}";
else
	hName="$(dmidecode -s chassis-type | head -1 | tr [A-Z] [a-z])-${bootID}";
fi

hostnamectl set-hostname $hName;
sed -i "s/immudex/${hName}/g" /etc/hosts;
echo $hName | sudo tee /etc/hostname > /dev/null;
