#!/bin/bash

GREEN="\e[32m";
YELLOW="\e[33m";
BLUE="\e[34m";
ENDCOLOR="\e[0m";

if [ -f /tmp/yt.html ]; then rm /tmp/yt.html; fi
if [ -f /tmp/yt.csv ]; then rm /tmp/yt.csv; fi

query=$(echo $* | sed 's/ /+/g');

wget https://youtube.com/results?search_query=$query -O /tmp/yt.html;

sed -i 's/,/\n/g' /tmp/yt.html;

listOfVideos=$(grep -n '^{\"url' /tmp/yt.html | cut -d ":" -f 1 | awk '{printf $1" "}');

numberOfListElements=$(echo $listOfVideos | wc -w);
i=1;
lp=1;
while [ $i -le $numberOfListElements ]; do
  if [ $i -eq $numberOfListElements ]; then
    ln1=$(echo $listOfVideos | cut -d " " -f $i);
    ln2='$';
  else
    j=$((i + 1));
    ln1=$(echo $listOfVideos | cut -d " " -f $i);
    ln2=$(echo $listOfVideos | cut -d " " -f $j);
  fi
  if sed -n "${ln1},${ln2}p" /tmp/yt.html | grep -q '"iconType":"LIVE"'; then
    i=$((i + 1)); continue;
  else
    title=$(sed -n "${ln1},${ln2}p" /tmp/yt.html | grep 'title' | head -1 | cut -d '"' -f 8);
    channel=$(sed -n "${ln1},${ln2}p" /tmp/yt.html | grep 'ownerText' | head -1 | cut -d '"' -f 8);
    duration=$(sed -n "${ln1},${ln2}p" /tmp/yt.html | grep 'simpleText' | sed -n '2p' | cut -d '"' -f 4);
    videoid=$(sed -n "${ln1},${ln2}p" /tmp/yt.html | grep 'videoId' | sed -n '2p' | cut -d '"' -f 4);
    if [ "$title" ] && [ "$channel" ] && [ "$duration" ] && [ "$videoid" ] && [ "$duration" != "SHORTS" ];  then
      echo -e "${lp}. ${GREEN}${title}${ENDCOLOR}";
      echo -e "   Channel: ${YELLOW}${channel}${ENDCOLOR}  Duration: ${BLUE}${duration}${ENDCOLOR}";
      echo "${lp},${videoid},${title},${channel},${duration}" >> /tmp/yt.csv;
    else
      i=$((i + 1)); continue;
    fi
  fi
  i=$((i + 1));
  lp=$((lp + 1));
done
echo -n "Put number of which video you want to hear: ";
read numberOfVideo;
title=$(sed -n "${numberOfVideo}p" /tmp/yt.csv | cut -d "," -f 3);
channel=$(sed -n "${numberOfVideo}p" /tmp/yt.csv | cut -d "," -f 4);
duration=$(sed -n "${numberOfVideo}p" /tmp/yt.csv | cut -d "," -f 5);
videoId=$(sed -n "${numberOfVideo}p" /tmp/yt.csv | cut -d "," -f 2);
clear;
echo -e "Title: ${GREEN}${title}${ENDCOLOR}";
echo -e "Channel: ${YELLOW}${channel}${ENDCOLOR} Duration: ${BLUE}${duration}${ENDCOLOR}";
echo "====================================================================";
mpv --ytdl-format=bestaudio ytdl://${videoId};
